FROM glavin001/alpine-python2-numpy-scipy

RUN apk --no-cache --update add git build-base

RUN git clone https://github.com/code-n-beer/SimoBotPython /pythonsimo
WORKDIR /pythonsimo

RUN pip install -r requirements.txt
COPY settings_pythonsimo.cfg /pythonsimo/Resources/settings.cfg

COPY LightweightApi.py /pythonsimo/

COPY pythonsimo-data/* /pythonsimo/Resources/

EXPOSE 8888
CMD python main.py
