FROM python:2.7-alpine

RUN apk --no-cache --update add git

# Disables caching for following commands
RUN echo $(date +"%T") > /tmp/bustcache

RUN git clone https://github.com/code-n-beer/SimoBotPython /pythonsimo
WORKDIR /pythonsimo

RUN pip install -r requirements.txt
COPY settings_pythonsimo.cfg /pythonsimo/Resources/settings.cfg

EXPOSE 8888
CMD python main.py
