FROM node:18-alpine

RUN apk add --no-cache icu-dev git python3 make g++
RUN adduser -D nodejs
USER nodejs
WORKDIR /home/nodejs
RUN npm install ircdjs && cd node_modules/ircdjs && npm install commander@2

EXPOSE 6667

CMD ["/home/nodejs/node_modules/ircdjs/bin/ircd.js"]
