#!/bin/bash

#authbind --deep mailin --webhook http://localhost/incoming_emails &
while [ 1 ]; do 
  echo "Kill dangling instances";
  if pgrep node; then
    kill -9 $(pgrep node||);
  fi
  echo "Starting new instance of SimoJS";
  NODE_TLS_REJECT_UNAUTHORIZED=0 node main.js;
done
