FROM glavin001/alpine-python2-numpy-scipy

RUN apk --no-cache --update add git build-base

RUN git clone https://github.com/code-n-beer/SimoBotPython /pythonsimodeps
WORKDIR /pythonsimodeps

RUN pip install -r requirements.txt
