FROM  huggingface/transformers-pytorch-gpu

WORKDIR /mlsimo

COPY requirements.txt /mlsimo/
RUN pip install -r requirements.txt
COPY server.py /mlsimo/

EXPOSE 8000
#CMD python3 server.py
CMD gunicorn -w 1 server:app

#RUN apk --no-cache --update add git build-base
#RUN git clone https://github.com/code-n-beer/SimoBotPython /pythonsimo
#COPY pythonsimo-data/* /pythonsimo/Resources/
#EXPOSE 8888
#CMD python main.py
